# Name(s)
**PUT YOUR FULL NAME(S) HERE**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [8]:
# YOUR SOLUTION HERE
#a=1000
import numpy as np
a = np.ones((6,4), dtype=np.int)*2
print(a)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [3]:
b = np.ones((6,4), dtype=np.int)
#np.fill_diagonal(b,3)
b[[0,1,2,3],[0,1,2,3]]=3
#note: inner arrays must be same size
print(b)

[[3 1 1 1]
 [1 3 1 1]
 [1 1 3 1]
 [1 1 1 3]
 [1 1 1 1]
 [1 1 1 1]]


## Exercise 3

In [4]:
c = a*b
print(c)


[[6 2 2 2]
 [2 6 2 2]
 [2 2 6 2]
 [2 2 2 6]
 [2 2 2 2]
 [2 2 2 2]]


In [ ]:
# YOUR SOLUTION HERE
The multiplication operation works differently than the dot operation. The multiplication by default works
by multiplying each element in one matrix by the corresponding element in the other matrix. Since 
the matrices are the same size, this operation will work. The dot product requires that the number of columns 
in the first matrix match the number of rows in the second matrix.

## Exercise 4

In [8]:
import numpy as np
transpA = np.dot(np.transpose(a), b)
print(transpA)

transpB = np.dot(a, np.transpose(b))
print(transpB)# YOUR SOLUTION HERE

print("The matrix that results from a dot product has the number of rows of the first matrix and the number of columns of the second matrix. Thus, it matters whether the transposed matrix is in the first or second position. ")

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]
[[12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]
 [12 12 12 12  8  8]]
The matrix that results from a dot product has the number of rows of the first matrix and the number of columns of the second matrix. Thus, it matters whether the transposed matrix is in the first or second position. 


## Exercise 5

In [21]:
print("my name is output")

my name is output


## Exercise 6

In [20]:
a = np.random.randint(2,6,(4,6))
b = np.random.randint(1, 10,(2,3))
print('a = \n', a)
print('\nb = \n', b)
print('\nsum of a =', np.sum(a))
print('\nsum of b columns =', np.sum(b, axis =0))
print('\nsum of a rows=', np.sum(a, axis = 1))
print('\nmean of b = ', np.mean(b))


a = 
 [[3 3 3 5 2 5]
 [3 5 2 2 3 4]
 [2 2 5 5 3 2]
 [2 2 5 2 2 3]]

b = 
 [[4 2 3]
 [8 6 8]]

sum of a = 75

sum of b columns = [12  8 11]

sum of a rows= [21 19 19 16]

mean of b =  5.166666666666667


## Exercise 7

In [51]:
a = np.random.randint(0,6,(3,6))

def countOnes(arr):
    count =0
    print(arr)
    for x in range(len(arr)):
        for y in range(len(arr[x])):
            if arr[x][y] == 1:
                count+=1
    print('counting ones with loop= ', count)
   
countOnes(a)

b = np.where(a == 1, 1, 0)
print('counting ones with np.where=',np.sum(b))
   

[[3 4 5 1 5 4]
 [2 4 2 3 1 3]
 [5 5 1 3 5 5]]
counting ones with loop=  3
counting ones with np.where= 3


## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [21]:
import pandas as pd
a1 = [[2,2,2,2], [2,2,2,2], [2,2,2,2], [2,2,2,2], [2,2,2,2],[2,2,2,2]]
a = pd.DataFrame(a1, dtype =int)
a

a = pd.DataFrame(2, index=np.arange(6), columns=np.arange(4))
a

0  1  2  3
0  2  2  2  2
1  2  2  2  2
2  2  2  2  2
3  2  2  2  2
4  2  2  2  2
5  2  2  2  2

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [35]:

b = pd.DataFrame(1, index=np.arange(6), columns=np.arange(4))
np.fill_diagonal(b.values,3)
b



0  1  2  3
0  3  1  1  1
1  1  3  1  1
2  1  1  3  1
3  1  1  1  3
4  1  1  1  1
5  1  1  1  1

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [36]:
c = a * b
print(c)

   0  1  2  3
0  6  2  2  2
1  2  6  2  2
2  2  2  6  2
3  2  2  2  6
4  2  2  2  2
5  2  2  2  2


## Exercise 11
Repeat exercise A.7 using a dataframe.

In [104]:
a = pd.DataFrame(np.random.randint(0, 3, size = (3, 4)))
print('arr =\n', a)
b = a.where(a==1)
count = np.sum(b.count())
print('number of ones =', count)

arr =
    0  1  2  3
0  0  1  1  1
1  1  0  2  1
2  2  2  1  2
number of ones = 6


## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [187]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv", delimiter=','
)
titanic_df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [178]:
titanic_df['name']

0                         Allen, Miss. Elisabeth Walton
1                        Allison, Master. Hudson Trevor
2                          Allison, Miss. Helen Loraine
3                  Allison, Mr. Hudson Joshua Creighton
4       Allison, Mrs. Hudson J C (Bessie Waldo Daniels)
                             ...                       
1304                               Zabour, Miss. Hileni
1305                              Zabour, Miss. Thamine
1306                          Zakarian, Mr. Mapriededer
1307                                Zakarian, Mr. Ortin
1308                                 Zimmerman, Mr. Leo
Name: name, Length: 1309, dtype: object

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [189]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv", delimiter=','
)
titanic_df.set_index('sex', inplace=True)
df = titanic_df.loc['female']
df


pclass  survived                                             name  \
sex                                                                         
female       1         1                    Allen, Miss. Elisabeth Walton   
female       1         0                     Allison, Miss. Helen Loraine   
female       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
female       1         1                Andrews, Miss. Kornelia Theodosia   
female       1         1    Appleton, Mrs. Edward Dale (Charlotte Lamson)   
...        ...       ...                                              ...   
female       3         1  Whabee, Mrs. George Joseph (Shawneene Abi-Saab)   
female       3         1                 Wilkes, Mrs. James (Ellen Needs)   
female       3         1          Yasbeck, Mrs. Antoni (Selini Alexander)   
female       3         0                             Zabour, Miss. Hileni   
female       3         0                            Zabour, Miss. Thamine   

         age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
sex                                                                          
female  29.0      0      0   24160  211.3375       B5        S    2    NaN   
female   2.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  25.0      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
female  63.0      1      0   13502   77.9583       D7        S   10    NaN   
female  53.0      2      0   11769   51.4792     C101        S    D    NaN   
...      ...    ...    ...     ...       ...      ...      ...  ...    ...   
female  38.0      0      0    2688    7.2292      NaN        C    C    NaN   
female  47.0      1      0  363272    7.0000      NaN        S  NaN    NaN   
female  15.0      1      0    2659   14.4542      NaN        C  NaN    NaN   
female  14.5      1      0    2665   14.4542      NaN        C  NaN  328.0   
female   NaN      1      0    2665   14.4542      NaN        C  NaN    NaN   

                              home.dest  
sex                                      
female                     St Louis, MO  
female  Montreal, PQ / Chesterville, ON  
female  Montreal, PQ / Chesterville, ON  
female                       Hudson, NY  
female              Bayside, Queens, NY  
...                                 ...  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  
female                              NaN  

[466 rows x 13 columns]

## Exercise 14
How do you reset the index?

In [50]:
titanic_df.reset_index(inplace=True)
titanic_df

index  pclass  survived  \
0         0       1         1   
1         1       1         1   
2         2       1         0   
3         3       1         0   
4         4       1         0   
...     ...     ...       ...   
1304   1304       3         0   
1305   1305       3         0   
1306   1306       3         0   
1307   1307       3         0   
1308   1308       3         0   

                                                 name     sex      age  sibsp  \
0                       Allen, Miss. Elisabeth Walton  female  29.0000      0   
1                      Allison, Master. Hudson Trevor    male   0.9167      1   
2                        Allison, Miss. Helen Loraine  female   2.0000      1   
3                Allison, Mr. Hudson Joshua Creighton    male  30.0000      1   
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.0000      1   
...                                               ...     ...      ...    ...   
1304                             Zabour, Miss. Hileni  female  14.5000      1   
1305                            Zabour, Miss. Thamine  female      NaN      1   
1306                        Zakarian, Mr. Mapriededer    male  26.5000      0   
1307                              Zakarian, Mr. Ortin    male  27.0000      0   
1308                               Zimmerman, Mr. Leo    male  29.0000      0   

      parch  ticket      fare    cabin embarked boat   body  \
0         0   24160  211.3375       B5        S    2    NaN   
1         2  113781  151.5500  C22 C26        S   11    NaN   
2         2  113781  151.5500  C22 C26        S  NaN    NaN   
3         2  113781  151.5500  C22 C26        S  NaN  135.0   
4         2  113781  151.5500  C22 C26        S  NaN    NaN   
...     ...     ...       ...      ...      ...  ...    ...   
1304      0    2665   14.4542      NaN        C  NaN  328.0   
1305      0    2665   14.4542      NaN        C  NaN    NaN   
1306      0    2656    7.2250      NaN        C  NaN  304.0   
1307      0    2670    7.2250      NaN        C  NaN    NaN   
1308      0  315082    7.8750      NaN        S  NaN    NaN   

                            home.dest  
0                        St Louis, MO  
1     Montreal, PQ / Chesterville, ON  
2     Montreal, PQ / Chesterville, ON  
3     Montreal, PQ / Chesterville, ON  
4     Montreal, PQ / Chesterville, ON  
...                               ...  
1304                              NaN  
1305                              NaN  
1306                              NaN  
1307                              NaN  
1308                              NaN  

[1309 rows x 15 columns]